### ISSUE TITLE
Classes not found

### ISSUE THREAD

**Issue by Yahasana** [meesoft/DiagramDesigner#2]
classes `TFloatEdit` and `TDoubleBufferredPanel` not found

`MainForm.TemplateFrame`, `MainForm.GridEdit` and  `MainForm.CanvasFrame` does not have corresponding component

[Fatal Error] DiagramDesigner.dpr(62): File not found: 'ImageDLLLoader.dcu'
[Fatal Error] DiagramReader.dpr(19): File not found: 'FastMM4.dcu'

**Comment by jkour** [comment]
Same here.
The Libs folder do not include them

**Comment by meesoft** [comment]
TDoubleBufferredPanel is in https://github.com/meesoft/DiagramDesigner/blob/master/Units/PanelFrame.pas#L90
TFloatEdit is in Units\ValueEdits.pas
FastMM4 is under Lib\FastMM4
I have added the missing ImageDLLLoader.pas
